version: "3"

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    networks:
      - webapp
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Nakarinh198799
      - MYSQL_DATABASE=construct_project
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root12345
  web-service:
    build: ./backend
    container_name: web-service
    ports:
      - "8081:8081"
    networks:
      - webapp
    depends_on:
      - mysql-db
  vue-app:
    build: ./frontend
    container_name: vue-app
    ports:
      - "8080:80"
    networks:
      - webapp
networks:
  webapp:
    driver: bridge
