version: "3"

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    networks:
      - webapp
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root12345
      - MYSQL_DATABASE=construct_project
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - ./db/data:/docker-entrypoint-initdb.d
  web-service:
    #build: ./backend
    image: nakarinh14/ooc-backend
    container_name: web-service
    ports:
      - "8081:8081"
    networks:
      - webapp
    depends_on:
      - mysql-db
networks:
  webapp:
    driver: bridge
